### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by maravilhosinga** [smshuja/parse-server-accountkit-auth#1]
Hello, after ading required code to index.js and package.json, Parse server has this error

Linux 2.6.32-042stab108.2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /root/angopapo/npm-debug.log

**Comment by smshuja** [comment]
This is a module for parse server, so you can't run "npm start" on this module. Are you using parse-server-example? Can you post your code here?

**Comment by maravilhosinga** [comment]
YES i'm using parse server example

// Example express application adding the parse-server module to expose Parse
// compatible API routes.

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');

var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'mXziCNou7uC3bEpESSdbaxCBmFjFPK894jA8AqFV',
  masterKey: process.env.MASTER_KEY || 'oyFU2JrC1ykRJP3LxOr2MVCPCKzoOf1KqDBgK7f0', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});

// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('Servidor angopapo esta executando');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function(req, res) {
  res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('Servidor angopapo esta na porta ' + port + '.');
});

// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);

// facebook AccountKit setup goes here
// Helper functions for accessing the Facebook Graph API.
var https = require('https');
var Parse = require('parse/node').Parse;
var crypto = require('crypto')

// Returns a promise that fulfills iff this user id is valid.
function validateAuthData(authData, config) {
  var appSecretProof = crypto.createHmac('sha256', config.appSecret).update(authData.access_token).digest('hex');
  return graphRequest('me/?access_token=' + authData.access_token + '&appsecret_proof=' + appSecretProof)
    .then((data) => {
      if (data && data.id == authData.id) {
        return;
      }
      throw new Parse.Error(
        Parse.Error.OBJECT_NOT_FOUND,
        'AccountKit auth is invalid for this user.');
    });
}

// Returns a promise that fulfills iff this app id is valid.
function validateAppId(appIds, authData, config) {
  return Promise.resolve();
}

// A promisey wrapper for FB graph requests.
function graphRequest(path) {
  return new Promise(function(resolve, reject) {
    https.get('https://graph.accountkit.com/v1.0/' + path, function(res) {
      var data = '';
      res.on('data', function(chunk) {
        data += chunk;
      });
      res.on('end', function() {
        data = JSON.parse(data);
        resolve(data);
      });
    }).on('error', function(e) {
      reject('Failed to validate this access token with Facebook AccountKit.');
    });
  });
}

module.exports = {
  validateAppId: validateAppId,
  validateAuthData: validateAuthData
};

**Comment by maravilhosinga** [comment]
Can you show step by step how to use this module please??

**Comment by smshuja** [comment]
You are doing it wrong. Don't clone or download this repository. Clone parse-server-example and follow their instructions https://github.com/ParsePlatform/parse-server-example/blob/master/README.md

In the parse-server-example folder run 

`npm install -S parse-server-accountkit-auth`

This will make install this module in node_modules folder. Don't change anything in the module.

Edit the index.js file in parse-server-example and configure ParseServer with oauth, you can find this in parse server [docs](https://github.com/ParsePlatform/parse-server/wiki/OAuth)

```
oauth: {
      accountkit: {
        module: 'parse-server-accountkit-auth',
        appSecret: 'YOUR_APP_SECRET'
      },
  },
```

**Comment by maravilhosinga** [comment]
Thanks, 
Then inside android, i used this. 
Now one more help to how to link Android or iOS AccountKit to work with Parse server ???

public static int APP_REQUEST_CODE = 99;

public void onLoginPhone(final View view) {
  final Intent intent = new Intent(getActivity(), AccountKitActivity.class);
  AccountKitConfiguration.AccountKitConfigurationBuilder configurationBuilder =
    new AccountKitConfiguration.AccountKitConfigurationBuilder(
      LoginType.PHONE,
      AccountKitActivity.ResponseType.CODE); // or .ResponseType.TOKEN
  // ... perform additional configuration ...
  intent.putExtra(
    AccountKitActivity.ACCOUNT_KIT_ACTIVITY_CONFIGURATION,
    configurationBuilder.build());
  startActivityForResult(intent, APP_REQUEST_CODE);
}
